{{- if and .Values.cluster.enabled (eq .Values.mishards.discoveryClassName "kubernetes") }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "milvus.fullname" . }}-pods-list
rules:
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["list", "get", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "milvus.fullname" . }}-pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "milvus.fullname" . }}-pods-list
  apiGroup: rbac.authorization.k8s.io
{{- end -}}