cache:
  insertBufferSize: 1GB
  cacheSize: 8GB

resources:
  limits:
    memory: "12Gi"
    cpu: "4.0"
    aliyun.com/gpu-mem: 2 # GiB
  requests:
    memory: "8Gi"
    cpu: "2.0"

gpu:
  enabled: true
  cacheSize: 2GB
  searchDevices:
    - gpu0
  buildIndexDevices:
    - gpu0

mysql:
  enabled: false
